apiVersion: v1
kind: Service
metadata:
  name: rocket-ecommerce-main-svc-b
  labels:
    app: rocket-ecommerce-main-svc-b
  namespace: prodv2-b-05-03-2026
spec:
  type: LoadBalancer
  selector:
    app: rocket-ecommerce-main-b-05-03-2026
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rocket-ecommerce-main-cm-b
  namespace: prodv2-b-05-03-2026
data:
  DEMO_MODE: "True"
  DEBUG: "True"
---
apiVersion: v1
kind: Secret
metadata:
  name: rocket-ecommerce-main-secret-b
  namespace: prodv2-b-05-03-2026
type: Opaque
data:
  STRIPE_PUBLISHABLE_KEY: cGtfdGVzdF81MVQ2dmZXQ3VxVW1TS1pWdGJ0MndWdDFOVEFmZTVYd1dURGtCQXBnOWp3dFVWSUxubzdzclRoZHB2Smt2cnljVFpJZHZjdGpvN2ZSbWRwTUNHdjVLUHQ4ODAwbHJ4eTZEUXc=
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVQ2dmZXQ3VxVW1TS1pWdDJhSTJDMVpaS0ZQR2xUaVljWldQbE13SUtLZFJrY0FxbXB4VnZUWDVkSVU1OG9wc2RTWkVIdlJ5alAxVDhHNU9WMjZ3djcxRzAwS1JvWVNNV3U=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-ecommerce-main-b-05-03-2026
  labels:
    app: rocket-ecommerce-main-b-05-03-2026
    env: production
    tier: frontend
  namespace: prodv2-b-05-03-2026
spec:
  selector:
    matchLabels:
      app: rocket-ecommerce-main-b-05-03-2026
  replicas: 3
  template:
    metadata:
      labels:
        app: rocket-ecommerce-main-b-05-03-2026
        env: production
        tier: frontend
    spec:
      containers:
      - name: rocket-ecommerce-main-b-05-03-2026
        image: sonikast1/rocket-ecommerce-main:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: rocket-ecommerce-main-cm-b
        env:
          - name: STRIPE_PUBLISHABLE_KEY
            valueFrom:
              secretKeyRef:
                name: rocket-ecommerce-main-secret-b
                key: STRIPE_PUBLISHABLE_KEY
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: rocket-ecommerce-main-secret-b
                key: STRIPE_SECRET_KEY
        ports:
        - containerPort: 5005