apiVersion: v1
kind: Service
metadata:
  name: django-adminlte-svc-b
  labels:
    app: django-adminlte-svc-b
  namespace: prodv2-b-05-03-2026
spec:
  type: ClusterIP
  selector:
    app: django-adminlte-b-05-03-2026
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-adminlte-b-05-03-2026
  labels:
    app: django-adminlte-b-05-03-2026
  namespace: prodv2-b-05-03-2026
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-adminlte-b-05-03-2026
  template:
    metadata:
      labels:
        app: django-adminlte-b-05-03-2026
    spec:
      containers:
      - name: django-adminlte-b-05-03-2026
        imagePullPolicy: IfNotPresent
        image: sonikast1/django-adminlte:latest
        ports:
        - containerPort: 5005
---